version: '3'
services:
  react-app:
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    ports:
      - "1234:1234"
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27017:27017"
    volumes:
      - local
  

